version: '3.8'

# 開発環境用 Docker Compose
# フロントエンドはローカルで npm start を実行してください (Vercel環境に合わせるため)
# 使い方:
#   1. docker-compose up -d でバックエンドを起動
#   2. cd frontend && npm start でフロントエンドを起動

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: markitdown-backend-dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    volumes:
      - ./backend/app:/app
      - ./backend/uploads:/uploads
      - ./backend/converted:/converted
    networks:
      - markitdown-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  markitdown-network:
    driver: bridge

volumes:
  uploads:
  converted: